
import java.awt.HeadlessException;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import smusemiv.connection.connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class editimport extends javax.swing.JInternalFrame {

    /**
     * Creates new form editimport
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public editimport() {
        initComponents();
        conn = connection.getConnection();
        this.fillImportTable();
        this.fillCountry();
        this.fillHscode();
        this.fillImporter();
        this.fillOffice();
        import_panel.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        importTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        import_panel = new javax.swing.JPanel();
        qty = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        office = new javax.swing.JComboBox();
        offName = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        eMsg = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        importer = new javax.swing.JTextField();
        value = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sex = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        size = new javax.swing.JTextField();
        goods = new javax.swing.JTextField();
        country_code = new javax.swing.JComboBox();
        country = new javax.swing.JTextField();
        passport = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        flight = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        duty = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        currency = new javax.swing.JTextField();
        hscode = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dept_date = new datechooser.beans.DateChooserCombo();
        contact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        arrival = new datechooser.beans.DateChooserCombo();
        importer_code = new javax.swing.JComboBox();
        boarding = new javax.swing.JTextField();
        unit = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        impId = new javax.swing.JLabel();
        delBtn = new javax.swing.JButton();
        print = new javax.swing.JButton();
        searchPassport = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        frmdate = new datechooser.beans.DateChooserCombo();
        searchBtn = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        todate = new datechooser.beans.DateChooserCombo();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Edit Export");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Export Declaration form");

        jLabel1.setFont(new java.awt.Font("GaramondNo4CyrTCYMed", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TIA CUSTOMS, Counter Section");

        importTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        importTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(importTable);

        jLabel11.setText("Last_dept_date");

        jLabel9.setText("Boarding No.");

        jLabel16.setText("Quantity");

        office.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select..." }));
        office.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                officeItemStateChanged(evt);
            }
        });

        jLabel20.setText("Sex");

        eMsg.setForeground(new java.awt.Color(230, 17, 17));
        eMsg.setText("eMsg");

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        value.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valueFocusLost(evt);
            }
        });

        jLabel18.setText("Total duty to be paid");

        jLabel10.setText("Contact No.");

        sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel15.setText("Unit");

        jLabel23.setText("Name of Goods");

        jLabel6.setText("Flight no.");

        country_code.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--" }));
        country_code.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                country_codeItemStateChanged(evt);
            }
        });

        country.setEditable(false);

        jLabel13.setText("HSCODE");

        jLabel8.setText("Address");

        jLabel14.setText("Size");

        desc.setText("desc");

        jLabel3.setText("Select your office code");

        jLabel12.setText("Arrival_date");

        currency.setEditable(false);
        currency.setText("NPR");

        hscode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hscodeItemStateChanged(evt);
            }
        });
        hscode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hscodeActionPerformed(evt);
            }
        });

        jLabel17.setText("Currency");

        jLabel22.setText("Total Value");

        jLabel5.setText("Country of Departure");

        dept_date.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));

    jLabel7.setText("Passport No.");

    arrival.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));

importer_code.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personal" }));
importer_code.addItemListener(new java.awt.event.ItemListener() {
    public void itemStateChanged(java.awt.event.ItemEvent evt) {
        importer_codeItemStateChanged(evt);
    }
    });

    unit.setEditable(false);
    unit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            unitActionPerformed(evt);
        }
    });

    jLabel4.setText("Importer");

    impId.setText("impId");

    delBtn.setText("Delete this item");
    delBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            delBtnActionPerformed(evt);
        }
    });

    print.setText("Print");
    print.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            printActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout import_panelLayout = new javax.swing.GroupLayout(import_panel);
    import_panel.setLayout(import_panelLayout);
    import_panelLayout.setHorizontalGroup(
        import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(import_panelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, import_panelLayout.createSequentialGroup()
                    .addComponent(impId)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                    .addComponent(eMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(import_panelLayout.createSequentialGroup()
                    .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(import_panelLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(import_panelLayout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addComponent(jLabel15)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel17)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(currency, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(112, 112, 112))
                .addGroup(import_panelLayout.createSequentialGroup()
                    .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(import_panelLayout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(duty, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(import_panelLayout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(goods, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(import_panelLayout.createSequentialGroup()
                            .addGap(172, 172, 172)
                            .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(62, 62, 62)
                            .addComponent(delBtn)
                            .addGap(90, 90, 90)
                            .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(import_panelLayout.createSequentialGroup()
                                    .addGap(87, 87, 87)
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(hscode, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(import_panelLayout.createSequentialGroup()
                                    .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(import_panelLayout.createSequentialGroup()
                                            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(flight, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(boarding, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(office, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(importer_code, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(country_code, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(import_panelLayout.createSequentialGroup()
                                                    .addGap(216, 216, 216)
                                                    .addComponent(offName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(import_panelLayout.createSequentialGroup()
                                                    .addGap(34, 34, 34)
                                                    .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(importer, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(import_panelLayout.createSequentialGroup()
                                                            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel12))
                                                            .addGap(20, 20, 20)
                                                            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(arrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addGroup(import_panelLayout.createSequentialGroup()
                                                                .addComponent(jLabel10)
                                                                .addGap(22, 22, 22)
                                                                .addComponent(contact))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, import_panelLayout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(passport, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                        .addComponent(dept_date, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    import_panelLayout.setVerticalGroup(
        import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(import_panelLayout.createSequentialGroup()
            .addGap(0, 0, 0)
            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(office, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(offName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(importer_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(importer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(country_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(import_panelLayout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11))
                .addGroup(import_panelLayout.createSequentialGroup()
                    .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(passport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(arrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGroup(import_panelLayout.createSequentialGroup()
                    .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(flight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boarding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addGap(7, 7, 7)
                    .addComponent(dept_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(import_panelLayout.createSequentialGroup()
                    .addComponent(desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(hscode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel23)
                .addComponent(goods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel22)
                    .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel18)
                .addComponent(duty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(eMsg)
                .addComponent(impId))
            .addGap(1, 1, 1)
            .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Save)
                .addComponent(delBtn)
                .addComponent(print))
            .addContainerGap())
    );

    jScrollPane2.setViewportView(import_panel);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(46, 46, 46))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addGap(7, 7, 7)
            .addComponent(jScrollPane2))
    );

    searchPassport.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            searchPassportKeyTyped(evt);
        }
    });

    jLabel19.setText("Search by PP No.");

    jLabel21.setText("Search by Arrival date :");

    frmdate.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
frmdate.setFormat(2);
frmdate.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);

searchBtn.setText("Search");
searchBtn.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        searchBtnActionPerformed(evt);
    }
    });

    jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel24.setForeground(new java.awt.Color(255, 0, 0));
    jLabel24.setText("FROM:");

    jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel25.setForeground(new java.awt.Color(255, 0, 0));
    jLabel25.setText("TO:");

    todate.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
todate.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(jLabel19)
        .addGap(18, 18, 18)
        .addComponent(searchPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(29, 29, 29)
        .addComponent(jLabel21)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel24)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(frmdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel25)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(todate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(searchBtn)
        .addContainerGap())
    .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(searchPassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel24))
                .addComponent(frmdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(searchBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(todate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importTableMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        try{
            // enable update button and desable Register button
            int row = importTable.getSelectedRow();
            String Table_click = (importTable.getModel().getValueAt(row, 0).toString());

            String sql = "Select * from import where `sn` =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,Table_click);
            rs = pst.executeQuery();

            if(rs.next()){
                import_panel.show();
//                office.setSelectedItem(new ComboboxItem(rs.getString("office_code"),""));
                System.out.println("country " + rs.getString("country_departure"));
                System.out.println("importer " + rs.getString("importer_code"));
                System.out.println("importer " + rs.getString("importer"));
//                ComboboxItem c = new ComboboxItem(rs.getString("importer"), rs.getString("importer_code"));
//                System.out.println(c);
//                importer_code.setSelectedItem(c);
//                
                
                
                country_code.setSelectedItem(rs.getString("country_departure"));
                flight.setText(rs.getString("flight_no"));
                passport.setText(rs.getString("passport_no"));
                boarding.setText(rs.getString("boarding_pass_no"));
                contact.setText(rs.getString("contact"));
                sex.setSelectedItem(rs.getString("sex"));
                address.setText(rs.getString("address"));
                dept_date.setText(rs.getString("last_depart_date"));
                arrival.setText(rs.getString("arrival_date"));
                hscode.setSelectedItem(rs.getString("hscode"));
                goods.setText(rs.getString("name_of_goods"));
                size.setText(rs.getString("size"));
                unit.setText(rs.getString("unit"));
                qty.setText(rs.getString("qty"));
                currency.setText(rs.getString("currency"));
                value.setText(rs.getString("value"));
                duty.setText(rs.getString("duty"));
                
                impId.setText(rs.getString("sn"));
                impId.hide();
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_importTableMouseClicked

    private void fillOffice(){
        try{
            String sql = "SELECT * FROM office";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //Vector model = new Vector();
             
            while(rs.next()){
                String code = rs.getString("officeCode");
                String name = rs.getString("officeName");
                office.addItem(new ComboboxItem(code,name));
                
               
            }
            
        } 
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void fillImporter(){
        try{
            String sql = "SELECT Code,Cmp_name FROM cmptbl order by Code";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //Vector model = new Vector();
             
            while(rs.next()){
                String name = rs.getString("Cmp_name");
                String code = rs.getString("Code");
                importer_code.addItem(new ComboboxItem(name,code));
                
               
            }
            
        } 
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void fillCountry(){
        try{
            String sql = "SELECT * FROM country order by Code";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //Vector model = new Vector();
             
            while(rs.next()){
                
                String code = rs.getString("Country");
                String name = rs.getString("Code");
                
                country_code.addItem(new ComboboxItem(code,name));
                
               
            }
            
        } 
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void fillHscode(){
        try{
            String sql = "SELECT * FROM hscode order by hscode";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //Vector model = new Vector();
             
            while(rs.next()){
                
                String code = rs.getString("goods_type");
                String name = rs.getString("hscode");
                int siz = rs.getInt("size");
                String unit = rs.getString("unit");
                int rt = rs.getInt("rate");
                
                hscode.addItem(new hsCombo(code,name,siz,unit,rt));
                
               
            }
            
        } 
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }
    
    
    
    private void officeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_officeItemStateChanged
        // TODO add your handling code here:
        String offcode = office.getSelectedItem().toString();
        try{
            String sql = "Select OfficeName from office where officeCode = '"+offcode + "'";
            pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                offName.setText(rs.getString("OfficeName"));
            }
            else{
                offName.setText("");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_officeItemStateChanged

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String imp = importer.getText();
        String addr = address.getText();
        String boad = boarding.getText();

        String cont = contact.getText();
        String f_flight = flight.getText();
        String c_country = country.getText();
        String curr = currency.getText();
        //String dept_d = dept_date.getText();
        DateFormat df = new SimpleDateFormat("Y-MM-dd");
        String ariv_dt = df.format(arrival.getSelectedDate().getTime());
        //chose_date.setText(formattedDate);
        String dept_d = df.format(dept_date.getSelectedDate().getTime());

        String d_desc = desc.getText();
        String d_duty = duty.getText();
        String good = goods.getText();
        String v_value = value.getText();
        String s_size = size.getText();
        String q_qty = qty.getText();
        String p_port = passport.getText();

        //int ofc = office.getSelectedIndex();

        ComboboxItem item = (ComboboxItem) office.getSelectedItem();
        String offCode = item.getCode();

        hsCombo hs = (hsCombo) hscode.getSelectedItem();
        String Unit = hs.getUnit();
        int siz = hs.getSize();
        int HRate = hs.getRate();
        String hRate = Integer.toString(HRate);
        String hsCode = hs.getCode();

        String sx = sex.getSelectedItem().toString();

        String importerCode = importer_code.getSelectedItem().toString();

        String eMessage = "";

        if("".equals(addr)){
            eMessage+="Address field is blank <br/>";
            address.grabFocus();
        }
        if("".equals(boad)){
            eMessage+="Boarding field is blank <br/>";
            boarding.grabFocus();
        }
        if("".equals(ariv_dt)){
            eMessage+="Arrival field is blank <br/>";
            arrival.grabFocus();
        }
        if ("".equals(cont)){
            eMessage+="Contact field is blank <br/>";
            contact.grabFocus();
        }
        if("".equals(f_flight)){
            eMessage+="flight no. field is blank<br/>";
            flight.grabFocus();
        }
        if("".equals(c_country)){
            eMessage+="country field is blank<br/>";
            country.grabFocus();
        }
        if("".equals(curr)){
            eMessage+="currency field is blank<br/>";
            currency.grabFocus();
        }
        if("".equals(dept_d)){
            eMessage+="Dept date field is blank<br/>";
            dept_date.grabFocus();
        }
        if("".equals(d_desc)){
            eMessage+="Desc field is blank<br/>";
            desc.grabFocus();
        }
        if("".equals(d_duty)){
            eMessage+="Duty date field is blank<br/>";
            duty.grabFocus();
        }
        if("".equals(good)){
            eMessage+="Goods field is blank<br/>";
            goods.grabFocus();
        }
        if("".equals(v_value)){
            eMessage+="Total Value field is blank<br/>";
            value.grabFocus();
        }
        if("".equals(s_size)){
            eMessage+="Size field is blank<br/>";
            size.grabFocus();
        }
        if("".equals(q_qty)){
            eMessage+="Quality field is blank<br/>";
            qty.grabFocus();
        }
        if("".equals(p_port)){
            eMessage+="Passport no. field is blank<br/>";

            if(!"".equals(eMessage))
            eMsg.setText("<html><body>"+eMessage+"</body></html>");
            passport.grabFocus();

        }else{
            try{
                String sql = "UPDATE import SET office_code = ?,importer_code = ?,importer = ?,country_departure = ?,`flight_no` = ?,`passport_no` = ? ,sex = ?,contact = ?,boarding_pass_no = ?,last_depart_date = ?,`arrival_date` = ?,address = ?,hscode = ?,`name_of_goods` = ?,size = ?,unit = ? ,qty = ?,currency = ?,value = ?,`tax_rate` = ?,duty = ? Where `sn` = ?";

                String[] params = {offCode,importerCode, imp,c_country,f_flight,
                    p_port,sx, cont, boad, dept_d, ariv_dt,addr,hsCode, good,
                    s_size, Unit,q_qty,curr,v_value,hRate,d_duty, impId.getText()
                };
                if( smusemiv.connection.connection.dbExecute(sql, params) == 1){
                    JOptionPane.showMessageDialog(null, "Sucess");
                    this.fillImportTable();
                    import_panel.hide();
                }

            }catch(HeadlessException | SQLException e)
            {
                JOptionPane.showMessageDialog(this, e);
            }

        }
    }//GEN-LAST:event_SaveActionPerformed

    private void valueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valueFocusLost
        //calculation of duty
        int qt = parseInt(qty.getText());
        hsCombo hs = (hsCombo) hscode.getSelectedItem();
        String e = "" ;
        if(hs.getCode().equals("")){
            JOptionPane.showMessageDialog(this,"Please Select hscode");
            e = "error";
        }
        if("".equals(qt)){
            JOptionPane.showMessageDialog(this,"Enter Quantity");
            e = "error";
        }
        if("".equals(e)){
            int rate = hs.getRate();
            int val = parseInt(value.getText());

            int dty = (qt * val * rate)/100;

            duty.setText("" + dty+"");

        }

    }//GEN-LAST:event_valueFocusLost

    private void country_codeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_country_codeItemStateChanged
        // TODO add your handling code here:
        //String impcode = country_code.getSelectedItem().toString();
        ComboboxItem item = (ComboboxItem)country_code.getSelectedItem();
        //JOptionPane.showMessageDialog(this, item.getCode());
        country.setText(item.getCode().toString());

    }//GEN-LAST:event_country_codeItemStateChanged

    private void hscodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hscodeItemStateChanged
        // TODO add your handling code here:
        hsCombo item = (hsCombo) hscode.getSelectedItem();
        desc.setText(item.getCode());
        size.setText(""+item.getSize()+"");

        unit.setText(item.getUnit());
    }//GEN-LAST:event_hscodeItemStateChanged

    private void hscodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hscodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hscodeActionPerformed

    private void importer_codeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_importer_codeItemStateChanged
        // TODO add your handling code here:
        String impcode = importer_code.getSelectedItem().toString();
        try{
            String sql = "Select Cmp_name from cmptbl where Code = '"+impcode + "'";
            // System.out.println(sql);
            pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                importer.setText(rs.getString("Cmp_name"));
            }
            else{
                importer.setText("");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_importer_codeItemStateChanged

    private void unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        Date d = frmdate.getSelectedDate().getTime();
        DateFormat df = new SimpleDateFormat("Y-MM-dd");
        String arivfDate = df.format(d);
        Date dd = todate.getSelectedDate().getTime();
        String arivtoDate = df.format(dd);
        
        try{
            String sql = "select `sn`, `passport_no`,`importer_code`, `name_of_goods`,`arrival_date`,`duty` from import WHERE `arrival_date` between '"+arivfDate+"' and '"+arivtoDate +"'";
            this.fillImportTable(sql);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        

    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchPassportKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPassportKeyTyped
        // TODO add your handling code here:
        String pp = searchPassport.getText();
        String sql = "select `sn`, `passport_no`,`importer_code`, `name_of_goods`,`arrival_date`,`duty` from import WHERE `passport_no` like '%"+pp+"%'";
        this.fillImportTable(sql);
    }//GEN-LAST:event_searchPassportKeyTyped

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
       if(JOptionPane.showConfirmDialog(null, "Are u Sure ?", "Billing System", JOptionPane.OK_CANCEL_OPTION) == 0)
        {
            if(!("".equals(impId.getText()))){
                String uid = impId.getText(); 
                String Sql = "DELETE from import  where `S.no`=?"; 
                try {
                    pst = conn.prepareStatement(Sql);
                    pst.setString(1,uid);
                    pst.execute();
                    impId.setText("");
                    this.fillImportTable();
                } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(this, ex);
                }
                
                
            }
            else{
                delBtn.setVisible(false);
            }
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        int id = parseInt(impId.getText());
        if(id > 0){
            print p = new print(id);
            p.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Please Select Record First");
        }
        
    }//GEN-LAST:event_printActionPerformed

    private void fillImportTable(){
        
    
      DefaultTableModel dtm = new DefaultTableModel();
      
        
      
        try{
        String sql = "select `sn`, `passport_no`,`importer_code`, `name_of_goods`,`arrival_date`,`duty` from import";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery(sql);
        dtm.addColumn("SN");
        dtm.addColumn("Passport No");
        dtm.addColumn("Importer");
        dtm.addColumn("Goods");
        dtm.addColumn("Arival");
        dtm.addColumn("Duty");
        
        while(rs.next()){
            Object objData[] = new Object[6];
            for(int i = 0; i<6;i++){
                objData[i]= rs.getString(i+1);
            }
            dtm.addRow(objData);
        }
        //userTable.setModel(DbUtils.resultSetToTableModel(rs));
        
        importTable.setModel(dtm);
        importTable.getColumnModel().getColumn(0).setMinWidth(0);
        importTable.getColumnModel().getColumn(0).setMaxWidth(0);
        
        }
        
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
  
    //function overloading to pass sql;
    private void fillImportTable(String sql){
        
        DefaultTableModel dtm = new DefaultTableModel();
      
        
      
        try{
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery(sql);
        
        dtm.addColumn("SN");
        dtm.addColumn("Passport No");
        dtm.addColumn("Importer");
        dtm.addColumn("Goods");
        dtm.addColumn("Arival");
        dtm.addColumn("Duty");
        
        while(rs.next()){
            Object objData[] = new Object[6];
            for(int i = 0; i<6;i++){
                objData[i]= rs.getString(i+1);
            }
            dtm.addRow(objData);
        }
        //userTable.setModel(DbUtils.resultSetToTableModel(rs));
        
        importTable.setModel(dtm);
        importTable.getColumnModel().getColumn(0).setMinWidth(0);
        importTable.getColumnModel().getColumn(0).setMaxWidth(0);
        
        }
        
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JTextField address;
    private datechooser.beans.DateChooserCombo arrival;
    private javax.swing.JTextField boarding;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField country;
    private javax.swing.JComboBox country_code;
    private javax.swing.JTextField currency;
    private javax.swing.JButton delBtn;
    private datechooser.beans.DateChooserCombo dept_date;
    private javax.swing.JLabel desc;
    private javax.swing.JTextField duty;
    private javax.swing.JLabel eMsg;
    private javax.swing.JTextField flight;
    private datechooser.beans.DateChooserCombo frmdate;
    private javax.swing.JTextField goods;
    private javax.swing.JComboBox hscode;
    private javax.swing.JLabel impId;
    private javax.swing.JTable importTable;
    private javax.swing.JPanel import_panel;
    private javax.swing.JTextField importer;
    private javax.swing.JComboBox importer_code;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel offName;
    private javax.swing.JComboBox office;
    private javax.swing.JTextField passport;
    private javax.swing.JButton print;
    private javax.swing.JTextField qty;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchPassport;
    private javax.swing.JComboBox sex;
    private javax.swing.JTextField size;
    private datechooser.beans.DateChooserCombo todate;
    private javax.swing.JTextField unit;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
