
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import smusemiv.connection.connection;
import utilities.validator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kishor
 */
public class Editcompany extends javax.swing.JInternalFrame {

    /**
     * Creates new form Editcompany
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public Editcompany() {
        initComponents();
        conn = connection.getConnection();
        this.fillCompany();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        companySelect = new javax.swing.JComboBox();
        code = new javax.swing.JTextField();
        cmp_name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add / Edit Company");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add / Edit Company Details");

        jLabel2.setText("Add/Edit :");

        companySelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Add New" }));
        companySelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                companySelectItemStateChanged(evt);
            }
        });
        companySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companySelectActionPerformed(evt);
            }
        });

        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });

        jLabel3.setText("Pan No.:");

        jLabel4.setText("Name :");

        jLabel5.setText("Address:");

        delete.setText("Delete Record");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        save.setText("Save/Update");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmp_name, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(code)
                                .addComponent(companySelect, 0, 130, Short.MAX_VALUE)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(companySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmp_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void companySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companySelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companySelectActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void companySelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_companySelectItemStateChanged
        // TODO add your handling code here:
        String company = companySelect.getSelectedItem().toString();
        if(company.equals("Add New")){
            code.setText("");
            cmp_name.setText("");
            address.setText("");
            
            
        }else{
            try{
                String sql = "select * from cmptbl where code =?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, company);
                
                rs = pst.executeQuery();
                if(rs.next()){
                    code.setText(rs.getString("code"));
                    cmp_name.setText(rs.getString("cmp_name"));
                    address.setText(rs.getString("address"));
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
            
        }
        
    }//GEN-LAST:event_companySelectItemStateChanged

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String company = companySelect.getSelectedItem().toString();
        String Code = code.getText();
        String company_name = cmp_name.getText();
        String Address = address.getText();
        
        validator v  = new validator();
        String error = "";
        
        if (!v.validateName(Code)) {
            error += "Invalid Code \n";
            
        }
        if (!v.validateName(company_name)) {
            error += "Invalid Company Name \n";
        }
        if(!v.validateName(Address)) {
            error += "Invalid Address \n";
        }
        if(!"".equals(error)) {
            JOptionPane.showMessageDialog(null, error, "Error",JOptionPane.WARNING_MESSAGE);
            
        } else{
            if(company.equals("Add New")){
                code.setEditable(true);
                try{
                    String sql = "INSERT INTO cmptbl(`code`,`cmp_name`,`address`) values (?,?,?)"; 
                    pst = conn.prepareStatement(sql);

                    pst.setString(1,code.getText());
                    pst.setString(2,cmp_name.getText());
                    pst.setString(3,address.getText());

                    pst.execute();

                    JOptionPane.showMessageDialog(this, "Saved ");
                    clear();

                }catch(SQLException | HeadlessException e){
                    JOptionPane.showMessageDialog(this, e);
                }

            }else{
                try{
                 String sql = "UPDATE cmptbl SET `cmp_name` =?, `address` =? WHERE `code` = ?"; 
                    pst = conn.prepareStatement(sql);


                    pst.setString(1,cmp_name.getText());
                    pst.setString(2,address.getText());

                    pst.setString(3,code.getText());

                    pst.execute();

                    JOptionPane.showMessageDialog(this, "Updateed  ");
                    clear();
                }catch(SQLException | HeadlessException e){
                    JOptionPane.showMessageDialog(this, e);
                }
            }
        }
        
        
        
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
         // TODO add your handling code here:
       if(JOptionPane.showConfirmDialog(null, "Are u Sure ?", "Delete Company", JOptionPane.OK_CANCEL_OPTION) == 0)
        {
            if(!("".equals(code.getText()))){
                String cd = code.getText(); 
                String Sql = "DELETE from cmptbl  where `code`=?"; 
                try {
                    pst = conn.prepareStatement(Sql);
                    pst.setString(1,cd);
                    pst.execute();
                    clear();
                    this.fillCompany();
                    
                } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(this, ex);
                }
                
                
            }
            else{
                delete.setVisible(false);
            }
        }
        
    }//GEN-LAST:event_deleteActionPerformed
    private void clear(){
        companySelect.setSelectedIndex(0);
        code.setText((""));
        cmp_name.setText("");
        address.setText("");
        
    }
    
     private void fillCompany(){
        
         try{
            String sql = "SELECT * FROM cmptbl";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //Vector model = new Vector();
             
            while(rs.next()){
                String code = rs.getString("code");
                companySelect.addItem(code);              
               
            }
            
        } 
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField cmp_name;
    private javax.swing.JTextField code;
    private javax.swing.JComboBox companySelect;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
