
import java.awt.HeadlessException;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import smusemiv.connection.connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class export extends javax.swing.JInternalFrame {

    /**
     * Creates new form Import
     * 
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public export() {
        conn = connection.getConnection();
        initComponents();
        
        this.fillOffice();
        this.fillImporter();
        this.fillCountry();
        this.fillHscode();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        qty = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        office = new javax.swing.JComboBox();
        offName = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        eMsg = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        importer = new javax.swing.JTextField();
        value = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sex = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        clear_btn = new javax.swing.JButton();
        size = new javax.swing.JTextField();
        goods = new javax.swing.JTextField();
        country_code = new javax.swing.JComboBox();
        country = new javax.swing.JTextField();
        passport = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        flight = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        duty = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        currency = new javax.swing.JTextField();
        hscode = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dept_date = new datechooser.beans.DateChooserCombo();
        contact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        arrival = new datechooser.beans.DateChooserCombo();
        importer_code = new javax.swing.JComboBox();
        boarding = new javax.swing.JTextField();
        unit = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Import Data");

        jLabel1.setFont(new java.awt.Font("GaramondNo4CyrTCYMed", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TIA CUSTOMS, Counter Section");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Export Declaration form");

        jLabel11.setText("Last_dept_date");

        jLabel9.setText("Boarding No.");

        jLabel16.setText("Quantity");

        office.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select..." }));
        office.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                officeItemStateChanged(evt);
            }
        });

        jLabel20.setText("Sex");

        eMsg.setForeground(new java.awt.Color(230, 17, 17));
        eMsg.setText("eMsg");

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        value.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valueFocusLost(evt);
            }
        });

        jLabel18.setText("Total duty to be paid");

        jLabel10.setText("Contact No.");

        sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel15.setText("Unit");

        jLabel23.setText("Name of Goods");

        jLabel6.setText("Flight no.");

        clear_btn.setText("clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        country_code.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--" }));
        country_code.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                country_codeItemStateChanged(evt);
            }
        });

        country.setEditable(false);

        jLabel13.setText("HSCODE");

        jLabel8.setText("Address");

        jLabel14.setText("Size");

        desc.setText("desc");

        jLabel3.setText("Select your office code");

        jLabel12.setText("Arrival_date");

        currency.setEditable(false);
        currency.setText("NPR");

        hscode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hscodeItemStateChanged(evt);
            }
        });
        hscode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hscodeActionPerformed(evt);
            }
        });

        jLabel17.setText("Currency");

        jLabel22.setText("Total Value");

        jLabel5.setText("Country of Departure");

        dept_date.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));

    jLabel7.setText("Passport No.");

    arrival.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Lucida Grande", java.awt.Font.PLAIN, 13),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));

importer_code.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Personal" }));
importer_code.addItemListener(new java.awt.event.ItemListener() {
    public void itemStateChanged(java.awt.event.ItemEvent evt) {
        importer_codeItemStateChanged(evt);
    }
    });

    unit.setEditable(false);
    unit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            unitActionPerformed(evt);
        }
    });

    jLabel4.setText("Importer");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(eMsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addComponent(jLabel15)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel17)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(currency, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addGap(112, 112, 112))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel18)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(duty, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel23)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(goods, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(198, 198, 198)
                    .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addComponent(jLabel13)
                            .addGap(18, 18, 18)
                            .addComponent(hscode, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(flight, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(boarding, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(office, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(importer_code, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(country_code, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(216, 216, 216)
                                            .addComponent(offName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(importer, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel12))
                                                    .addGap(20, 20, 20)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(arrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addGap(22, 22, 22)
                                                        .addComponent(contact))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(passport, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addComponent(dept_date, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(office, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(offName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(importer_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(importer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(country_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(passport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(arrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(flight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boarding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addGap(7, 7, 7)
                    .addComponent(dept_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(28, 28, 28))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(hscode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel23)
                .addComponent(goods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel22)
                    .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel18)
                .addComponent(duty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(eMsg)
            .addGap(26, 26, 26)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Save)
                .addComponent(clear_btn))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 109, Short.MAX_VALUE)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addGap(12, 12, 12)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void officeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_officeItemStateChanged
        // TODO add your handling code here:
        String offcode = office.getSelectedItem().toString();
        try{
            String sql = "Select OfficeName from office where officeCode = '"+offcode + "'";
            pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                offName.setText(rs.getString("OfficeName"));
            }
            else{
                offName.setText("");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_officeItemStateChanged

    private void importer_codeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_importer_codeItemStateChanged
        // TODO add your handling code here:
        String impcode = importer_code.getSelectedItem().toString();
        try{
            String sql = "Select Cmp_name from cmptbl where Code = '"+impcode + "'";
            // System.out.println(sql);
            pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                importer.setText(rs.getString("Cmp_name"));
            }
            else{
                importer.setText("");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_importer_codeItemStateChanged

    private void hscodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hscodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hscodeActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        this.clearForm();
        
    }//GEN-LAST:event_clear_btnActionPerformed
    
    private void clearForm(){
        // TODO add your handling code here:
        importer.setText("");
        address.setText("");
        boarding.setText("");
        arrival.setText("");
        contact.setText("");
        flight.setText("");
        country.setText("");
        currency.setText("");
        dept_date.setText("");
        desc.setText("");
        duty.setText("");
        goods.setText("");
        value.setText("");
        size.setText("");
        qty.setText("");
        passport.setText("");
        eMsg.setText("");
    }
    private void fillOffice(){
        try{
            String sql = "SELECT * FROM office";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //Vector model = new Vector();
             
            while(rs.next()){
                String code = rs.getString("officeCode");
                String name = rs.getString("officeName");
                office.addItem(new ComboboxItem(code,name));
                
               
            }
            
        } 
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void fillImporter(){
        try{
            String sql = "SELECT Code,Cmp_name FROM cmptbl order by Code";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //Vector model = new Vector();
             
            while(rs.next()){
                String name = rs.getString("Cmp_name");
                String code = rs.getString("Code");
                importer_code.addItem(new ComboboxItem(name,code));
                
               
            }
            
        } 
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void fillCountry(){
        try{
            String sql = "SELECT * FROM country order by Code";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //Vector model = new Vector();
             
            while(rs.next()){
                
                String code = rs.getString("Country");
                String name = rs.getString("Code");
                
                country_code.addItem(new ComboboxItem(code,name));
                
               
            }
            
        } 
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void fillHscode(){
        try{
            String sql = "SELECT * FROM hscode order by hscode";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //Vector model = new Vector();
             
            while(rs.next()){
                
                String code = rs.getString("goods_type");
                String name = rs.getString("hscode");
                int siz = rs.getInt("size");
                String unit = rs.getString("unit");
                int rt = rs.getInt("rate");
                
                hscode.addItem(new hsCombo(code,name,siz,unit,rt));
                
               
            }
            
        } 
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
    }
    
    
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String imp = importer.getText();
        String addr = address.getText();
        String boad = boarding.getText();
        
        String cont = contact.getText();
        String f_flight = flight.getText();
        String c_country = country.getText();
        String curr = currency.getText();
        //String dept_d = dept_date.getText();
        DateFormat df = new SimpleDateFormat("Y-MM-dd");
        String ariv_dt = df.format(arrival.getSelectedDate().getTime()); 
        //chose_date.setText(formattedDate);
        String dept_d = df.format(dept_date.getSelectedDate().getTime());
        
        String d_desc = desc.getText();
        String d_duty = duty.getText();
        String good = goods.getText();
        String v_value = value.getText();
        String s_size = size.getText();
        String q_qty = qty.getText();
        String p_port = passport.getText();
        
        //int ofc = office.getSelectedIndex();
        String offCode = "";
        try{
            ComboboxItem off = (ComboboxItem) office.getSelectedItem();
            offCode = off.getCode();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex + "\n Select office code!!");
        }        
        hsCombo hs = (hsCombo) hscode.getSelectedItem();
        String Unit = hs.getUnit();
        int siz = hs.getSize();
        int hRate = hs.getRate();
        String hsCode = hs.toString();
        
        
        String sx = sex.getSelectedItem().toString();
        
        String importerCode = importer_code.getSelectedItem().toString();
        
        
        String eMessage = "";
        
        if("".equals(addr)){
            eMessage+="Address field is blank \n";
            address.grabFocus();
        }
        if("".equals(boad)){
            eMessage+="Boarding field is blank \n";
            boarding.grabFocus();
        }
        if("".equals(ariv_dt)){
            eMessage+="Arrival field is blank \n";
            arrival.grabFocus();
        }
        if ("".equals(cont)){
            eMessage+="Contact field is blank \n";
            contact.grabFocus();
        }
        if("".equals(f_flight)){
            eMessage+="flight no. field is blank \n";
            flight.grabFocus();
        }
        if("".equals(c_country)){
            eMessage+="country field is blank \n";
            country.grabFocus();
        }
        if("".equals(curr)){
            eMessage+="currency field is blank\n";
            currency.grabFocus();
        }
        if("".equals(dept_d)){
            eMessage+="Dept date field is blank \n";
            dept_date.grabFocus();
        }
        if("".equals(d_desc)){
            eMessage+="Desc field is blank<br/>";
            desc.grabFocus();
        }
        if("".equals(d_duty)){
            eMessage+="Duty date field is blank \n";
            duty.grabFocus();
        }
        if("".equals(good)){
            eMessage+="Goods field is blank \n";
            goods.grabFocus();
        }
        if("".equals(v_value)){
            eMessage+="Total Value field is blank \n";
            value.grabFocus();
        }
        if("".equals(s_size)){
            eMessage+="Size field is blank \n";
            size.grabFocus();
        }
        if("".equals(q_qty)){
            eMessage+="Quality field is blank \n";
            qty.grabFocus();
        }
        if("".equals(p_port)){
            eMessage+="Passport no. field is blank \n";
            
        
        if(!"".equals(eMessage))
            JOptionPane.showMessageDialog(passport, eMessage);
            passport.grabFocus();
            
        }else{
            try{
                String sql = "INSERT INTO export (office_code,importer_code,importer,country_departure,`flight_no`,`passport_no`,sex,contact,boarding_pass_no,last_depart_date,`arrival_date`,address,hscode,`name_of_goods`,size,unit,qty,currency,value,`tax_rate`,duty) Values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? )";
 
                pst = conn.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS);
                
                pst.setString(1,offCode);
                pst.setString(2,importerCode);
                pst.setString(3,imp);
                pst.setString(4,c_country);
                pst.setString(5,f_flight);
                pst.setString(6,p_port);
                pst.setString(7,sx);
                pst.setString(8,cont);
                pst.setString(9,boad);
                pst.setString(10,dept_d);
                pst.setString(11,ariv_dt);
                pst.setString(12,addr);
                pst.setString(13,hsCode);
                pst.setString(14,good);
                pst.setString(15,s_size);
                pst.setString(16,Unit);
                pst.setString(17,q_qty);
                pst.setString(18,curr);
                pst.setString(19,v_value);
                pst.setInt(20,hRate);
                pst.setString(21,d_duty);
                
                
                int numero = pst.executeUpdate();
                System.out.println(numero);
                int risultato = 0;
                rs = pst.getGeneratedKeys();
                if (rs.next()){
                    risultato = rs.getInt(1);
                }
                JOptionPane.showMessageDialog(passport,"Data sucessfully Added");
                this.clearForm();
//                System.out.println("data " + risultato);
//                print p = new print (risultato);
//                p.setVisible(true);
 
               

             }catch(HeadlessException | SQLException e)
             {
                 JOptionPane.showMessageDialog(this, e);
             }

            
            
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void country_codeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_country_codeItemStateChanged
        // TODO add your handling code here:
        //String impcode = country_code.getSelectedItem().toString();
        ComboboxItem item = (ComboboxItem)country_code.getSelectedItem();
        //JOptionPane.showMessageDialog(this, item.getCode());
        country.setText(item.getCode().toString());
        
    }//GEN-LAST:event_country_codeItemStateChanged

    private void hscodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hscodeItemStateChanged
        // TODO add your handling code here:
        hsCombo item = (hsCombo) hscode.getSelectedItem();
        desc.setText(item.getCode().toString());
        size.setText(""+item.getSize()+"");
        
        unit.setText(item.getUnit().toString());
    }//GEN-LAST:event_hscodeItemStateChanged

    private void unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitActionPerformed

    private void valueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valueFocusLost
        //calculation of duty
        int qt = parseInt(qty.getText());
        hsCombo hs = (hsCombo) hscode.getSelectedItem();
        String e = "" ; 
        if(hs.getCode().toString().equals("")){
            JOptionPane.showMessageDialog(this,"Please Select hscode");
            e = "error";
        }
        if("".equals(qt)){
            JOptionPane.showMessageDialog(this,"Enter Quantity");
            e = "error";
        }
        if("".equals(e)){
            int rate = hs.getRate();
            int val = parseInt(value.getText());
            
            int dty = (qt * val * rate)/100;
            
            duty.setText("" + dty+"");
            
            
        }
        
        
    }//GEN-LAST:event_valueFocusLost


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JTextField address;
    private datechooser.beans.DateChooserCombo arrival;
    private javax.swing.JTextField boarding;
    private javax.swing.JButton clear_btn;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField country;
    private javax.swing.JComboBox country_code;
    private javax.swing.JTextField currency;
    private datechooser.beans.DateChooserCombo dept_date;
    private javax.swing.JLabel desc;
    private javax.swing.JTextField duty;
    private javax.swing.JLabel eMsg;
    private javax.swing.JTextField flight;
    private javax.swing.JTextField goods;
    private javax.swing.JComboBox hscode;
    private javax.swing.JTextField importer;
    private javax.swing.JComboBox importer_code;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel offName;
    private javax.swing.JComboBox office;
    private javax.swing.JTextField passport;
    private javax.swing.JTextField qty;
    private javax.swing.JComboBox sex;
    private javax.swing.JTextField size;
    private javax.swing.JTextField unit;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
