
import java.awt.HeadlessException;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilities.userSession;
import smusemiv.connection.connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kishor
 */
public class importRelease extends javax.swing.JInternalFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    userSession eUser; 
    /**
     * Creates new form importRelease2
     * @param euser
     */
    public importRelease(userSession euser) {
        initComponents();
        conn = connection.getConnection();
        this.fillImportTable();
        this.eUser = euser;
        action_panel.hide();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        action_panel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        impId = new javax.swing.JLabel();
        print = new javax.swing.JButton();
        country_value = new java.awt.Label();
        office_code_value = new java.awt.Label();
        importer_value = new java.awt.Label();
        flght_value = new java.awt.Label();
        bording_value = new java.awt.Label();
        passport_value = new java.awt.Label();
        hscode_value = new java.awt.Label();
        goods_value = new java.awt.Label();
        jLabel24 = new javax.swing.JLabel();
        size_value = new java.awt.Label();
        unit_value = new java.awt.Label();
        jLabel19 = new javax.swing.JLabel();
        quantity_value = new java.awt.Label();
        jLabel20 = new javax.swing.JLabel();
        total_value = new java.awt.Label();
        jLabel21 = new javax.swing.JLabel();
        total_duty_paid_value = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        importReleaseTable = new javax.swing.JTable();
        importer_lbl = new javax.swing.JLabel();
        importer_code = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Relase Custom");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Import Release form");

        jLabel1.setFont(new java.awt.Font("GaramondNo4CyrTCYMed", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TIA CUSTOMS, Counter Section");

        jLabel9.setText("Boarding No.");

        Save.setText("Release");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        jLabel15.setText("Unit");

        jLabel23.setText("Name of Goods");

        jLabel6.setText("Flight no.");

        jLabel13.setText("HSCODE");

        jLabel3.setText("office code");

        jLabel5.setText("Country of Departure");

        jLabel7.setText("Passport No.");

        jLabel4.setText("Importer");

        impId.setText("impId");

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        country_value.setText("label1");

        office_code_value.setText("label1");

        importer_value.setText("label1");

        flght_value.setText("label1");

        bording_value.setText("label2");

        passport_value.setText("label2");

        hscode_value.setText("label2");

        goods_value.setText("label2");

        jLabel24.setText("Size");

        size_value.setText("label3");

        unit_value.setText("label3");

        jLabel19.setText("Quantity");

        quantity_value.setText("label3");

        jLabel20.setText("Total Value");

        total_value.setText("label3");

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 204, 0));
        jLabel21.setText("Total duty to be paid");

        total_duty_paid_value.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        total_duty_paid_value.setForeground(new java.awt.Color(51, 204, 0));
        total_duty_paid_value.setText("label2");

        javax.swing.GroupLayout action_panelLayout = new javax.swing.GroupLayout(action_panel);
        action_panel.setLayout(action_panelLayout);
        action_panelLayout.setHorizontalGroup(
            action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action_panelLayout.createSequentialGroup()
                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(action_panelLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(action_panelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(office_code_value, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(action_panelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel24)
                            .addComponent(impId))
                        .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(action_panelLayout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel6)))
                            .addGroup(action_panelLayout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(flght_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hscode_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(importer_value, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(action_panelLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel15)
                        .addGap(22, 22, 22)
                        .addComponent(unit_value, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addGap(22, 22, 22)
                        .addComponent(quantity_value, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_value, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(action_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(action_panelLayout.createSequentialGroup()
                        .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(country_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bording_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passport_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goods_value, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(action_panelLayout.createSequentialGroup()
                        .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(action_panelLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total_duty_paid_value, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(size_value, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        action_panelLayout.setVerticalGroup(
            action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(action_panelLayout.createSequentialGroup()
                        .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(office_code_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(importer_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(action_panelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(country_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(bording_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(action_panelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(flght_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(hscode_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(passport_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(goods_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel24)
                        .addComponent(size_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15)
                    .addComponent(jLabel19)
                    .addComponent(quantity_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(total_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(total_duty_paid_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(impId)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(print))
                .addContainerGap())
        );

        jScrollPane3.setViewportView(action_panel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        importReleaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        importReleaseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importReleaseTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                importReleaseTableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(importReleaseTable);

        importer_lbl.setText("Search By Importer Code");

        importer_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                importer_codeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(importer_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(importer_code, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importer_lbl)
                    .addComponent(importer_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String message = "There are commands in the Release Custom, really want to release?";
        String title = "Release Custom";
        String impid = impId.getText();
        Integer userId = this.eUser.getUserId();
        System.out.println(this.eUser.getUserId());
        // display the JOptionPane showConfirmDialog
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
          String sql = "INSERT INTO import_release(import_id,user_id) VALUES(?,?)";
          
          try{
                //String insertSQL = "INSERT INTO user (FirstName) values(?)";
                
                String[] pararms = {impid, userId.toString()};

                if (smusemiv.connection.connection.dbExecute(sql, pararms) == 1){
                    String sql2 = "UPDATE import set status = 1 WHERE sn = ?";
                    String[] pararms2 = {impid};
                    if( smusemiv.connection.connection.dbExecute(sql2, pararms2) == 1){
                        JOptionPane.showMessageDialog(null, "Sucess");
                        this.fillImportTable();
                        action_panel.hide(); 
                    }
                    
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "fail");
                }
            }
            catch(SQLException | HeadlessException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, e);
            }
          
          
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        int id = parseInt(impId.getText());
        if(id > 0){
            print p = new print(id);
            p.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Please Select Record First");
        }
    }//GEN-LAST:event_printActionPerformed

    private void importReleaseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importReleaseTableMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        try{
            // enable update button and desable Register button
            int row = importReleaseTable.getSelectedRow();
            String Table_click = (importReleaseTable.getModel().getValueAt(row, 0).toString());
            
            String sql = "Select * from import where `sn` =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,Table_click);
            rs = pst.executeQuery();

            if(rs.next()){
                action_panel.show();    
                //office.setSelectedItem(new ComboboxItem(rs.getString("Office_code"),""));
                String importerValue = rs.getString("importer_code").concat(" ").concat(rs.getString("importer"));
                importer_value.setText(importerValue);

                country_value.setText(rs.getString("country_departure"));
                flght_value.setText(rs.getString("flight_no"));
                passport_value.setText(rs.getString("passport_no"));
                bording_value.setText(rs.getString("boarding_pass_no"));
                hscode_value.setText(rs.getString("hscode"));
                goods_value.setText(rs.getString("name_of_goods"));
                size_value.setText(rs.getString("size"));
                unit_value.setText(rs.getString("unit"));
                quantity_value.setText(rs.getString("qty"));
                total_value.setText(rs.getString("value"));
                total_duty_paid_value.setText(rs.getString("duty"));

                impId.setText(rs.getString("sn"));
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_importReleaseTableMouseClicked

    private void importer_codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_importer_codeKeyTyped
        //         TODO add your handling code here:
        String importValue = importer_code.getText();
        String sql = "select `sn`, `passport_no`,`importer_code`, `name_of_goods`,`arrival_date`,`duty` from import WHERE `sn` like '%"+importValue+"%' and status=0";
        this.fillImportTable(sql);
    }//GEN-LAST:event_importer_codeKeyTyped
    private void fillImportTable(){
        
    
      DefaultTableModel dtm = new DefaultTableModel();
      
        
      
        try{
        String sql = "select `sn`, `passport_no`,`importer_code`, `name_of_goods`,`arrival_date`,`duty` from import where status=0";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery(sql);
        dtm.addColumn("SN");
        dtm.addColumn("Passport No");
        dtm.addColumn("Importer");
        dtm.addColumn("Goods");
        dtm.addColumn("Arival");
        dtm.addColumn("Duty");
        
        while(rs.next()){
            Object objData[] = new Object[6];
            for(int i = 0; i<6;i++){
                objData[i]= rs.getString(i+1);
            }
            dtm.addRow(objData);
        }
        //userTable.setModel(DbUtils.resultSetToTableModel(rs));
        
        importReleaseTable.setModel(dtm);
        importReleaseTable.getColumnModel().getColumn(0).setMinWidth(0);
        importReleaseTable.getColumnModel().getColumn(0).setMaxWidth(0);
        
        }
        
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    //function overloading to pass sql;
    private void fillImportTable(String sql){
        
        DefaultTableModel dtm = new DefaultTableModel();
      
        
      
        try{
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery(sql);
        
        dtm.addColumn("SN");
        dtm.addColumn("Passport No");
        dtm.addColumn("Importer");
        dtm.addColumn("Goods");
        dtm.addColumn("Arival");
        dtm.addColumn("Duty");
        
        while(rs.next()){
            Object objData[] = new Object[6];
            for(int i = 0; i<6;i++){
                objData[i]= rs.getString(i+1);
            }
            dtm.addRow(objData);
        }
        //userTable.setModel(DbUtils.resultSetToTableModel(rs));
        
        importReleaseTable.setModel(dtm);
        importReleaseTable.getColumnModel().getColumn(0).setMinWidth(0);
        importReleaseTable.getColumnModel().getColumn(0).setMaxWidth(0);
        
        }
        
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    private void importReleaseTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importReleaseTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_importReleaseTableMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JPanel action_panel;
    private java.awt.Label bording_value;
    private java.awt.Label country_value;
    private java.awt.Label flght_value;
    private java.awt.Label goods_value;
    private java.awt.Label hscode_value;
    private javax.swing.JLabel impId;
    private javax.swing.JTable importReleaseTable;
    private javax.swing.JTextField importer_code;
    private javax.swing.JLabel importer_lbl;
    private java.awt.Label importer_value;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label office_code_value;
    private java.awt.Label passport_value;
    private javax.swing.JButton print;
    private java.awt.Label quantity_value;
    private java.awt.Label size_value;
    private java.awt.Label total_duty_paid_value;
    private java.awt.Label total_value;
    private java.awt.Label unit_value;
    // End of variables declaration//GEN-END:variables
}
