
import java.io.IOException;
import java.net.URISyntaxException;
import utilities.userSession;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.xpath.XPathExpressionException;
import org.xml.sax.SAXException;
import utilities.centerDesktop;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kishor
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form dataentry
     */
    userSession eUser;
    public Menu(userSession eUser) {
        initComponents();
        this.eUser = eUser;
        
        username.setText(eUser.getUserName() +" / "+ eUser.getUserRole());
        this.userPermission();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void userPermission(){
        menu_add_user.setEnabled(false);
        menu_company.setEnabled(false);
        menu_country.setEnabled(false);
        menu_edit_user.setEnabled(false);
        menu_office.setEnabled(false);
        menu_tools.setEnabled(false);
        
        customs_import.setVisible(false);
        custom_export.setVisible(false);
        
        if (eUser.getUserRole()==3) { 
            // super user all 
            menu_tools.setEnabled(true);
            menu_add_user.setEnabled(true);
            menu_company.setEnabled(true);
            menu_country.setEnabled(true);
            menu_edit_user.setEnabled(true);
            menu_office.setEnabled(true);
            menu_tools.setEnabled(false);
            customs_import.setVisible(true);
            custom_export.setVisible(true);
        }
        
        if (eUser.getUserRole()== 2 ) { 
            // admin user
            menu_tools.setEnabled(true);
            menu_add_user.setEnabled(true);
            menu_company.setEnabled(true);
            menu_country.setEnabled(true);
            menu_edit_user.setEnabled(true);
            menu_office.setEnabled(true);
            customs_import.setVisible(true);
            custom_export.setVisible(true);
            
        }
        
        if (eUser.getUserRole()== 0 ) { 
            // import staff
            customs_import.setVisible(true);
        }
        
        if (eUser.getUserRole()==1) { 
            // export staff
            custom_export.setVisible(true);
        }

        
        
        
//        if((eUser.getUserRole()==2)){
//            menu_add_user.setEnabled(true);
//            menu_company.setEnabled(true);
//            menu_country.setEnabled(true);
//            menu_edit_user.setEnabled(true);
//            menu_office.setEnabled(true);
//            
//        }
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        main_menu = new javax.swing.JMenu();
        menu_add_user = new javax.swing.JMenuItem();
        menu_edit_user = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_company = new javax.swing.JMenuItem();
        menu_office = new javax.swing.JMenuItem();
        menu_country = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menu_logout = new javax.swing.JMenuItem();
        menu_exit = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        customs_import = new javax.swing.JMenu();
        data_input = new javax.swing.JMenuItem();
        edit_data = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        release_import = new javax.swing.JMenuItem();
        custom_export = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        report_by_date = new javax.swing.JMenu();
        report_date_wise = new javax.swing.JMenuItem();
        report_date_date_hscode = new javax.swing.JMenuItem();
        report_hscode = new javax.swing.JMenu();
        report_hs_code_s = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu9 = new javax.swing.JMenu();
        menu_tools = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        tools_restore = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        help_help = new javax.swing.JMenuItem();
        help_about = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CUSTOM MANAGEMENT SYSTEM");

        username.setText("username");

        jLabel1.setText("Welcome ");

        desktop.setBorder(new javax.swing.border.MatteBorder(null));
        desktop.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);
        jScrollPane1.setViewportView(desktop);

        jMenuBar1.setBackground(new java.awt.Color(204, 153, 0));
        jMenuBar1.setForeground(new java.awt.Color(51, 51, 255));

        main_menu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 51)));
        main_menu.setText("Main");

        menu_add_user.setText("Add User");
        menu_add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_add_userActionPerformed(evt);
            }
        });
        main_menu.add(menu_add_user);

        menu_edit_user.setText("Edit User");
        menu_edit_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_edit_userActionPerformed(evt);
            }
        });
        main_menu.add(menu_edit_user);
        main_menu.add(jSeparator1);

        menu_company.setText("Company (Add/Edit)");
        menu_company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_companyActionPerformed(evt);
            }
        });
        main_menu.add(menu_company);

        menu_office.setText("Office (Add/Edit)");
        menu_office.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_officeActionPerformed(evt);
            }
        });
        main_menu.add(menu_office);

        menu_country.setText("Country (Add/Edit)");
        menu_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_countryActionPerformed(evt);
            }
        });
        main_menu.add(menu_country);
        main_menu.add(jSeparator3);

        menu_logout.setText("Logout");
        menu_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_logoutActionPerformed(evt);
            }
        });
        main_menu.add(menu_logout);

        menu_exit.setText("Exit");
        menu_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_exitActionPerformed(evt);
            }
        });
        main_menu.add(menu_exit);

        jMenuBar1.add(main_menu);
        jMenuBar1.add(jMenu8);

        customs_import.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        customs_import.setText("Customs Import    ");

        data_input.setText("Data Input");
        data_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_inputActionPerformed(evt);
            }
        });
        customs_import.add(data_input);

        edit_data.setText("Edit Data");
        edit_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_dataActionPerformed(evt);
            }
        });
        customs_import.add(edit_data);
        customs_import.add(jSeparator2);

        release_import.setText("Release Import");
        release_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release_importActionPerformed(evt);
            }
        });
        customs_import.add(release_import);

        jMenuBar1.add(customs_import);

        custom_export.setText("Customs Export");

        jMenuItem4.setText("Enter Data");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        custom_export.add(jMenuItem4);

        jMenuItem5.setText("Edit Data");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        custom_export.add(jMenuItem5);
        custom_export.add(jSeparator5);

        jMenuItem7.setText("Release");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        custom_export.add(jMenuItem7);

        jMenuBar1.add(custom_export);
        jMenuBar1.add(jMenu10);

        jMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("Reports    ");

        report_by_date.setText("By date");

        report_date_wise.setText("Datewise");
        report_date_wise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_date_wiseActionPerformed(evt);
            }
        });
        report_by_date.add(report_date_wise);

        report_date_date_hscode.setText("Date and HSCODE");
        report_date_date_hscode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_date_date_hscodeActionPerformed(evt);
            }
        });
        report_by_date.add(report_date_date_hscode);

        jMenu2.add(report_by_date);

        report_hscode.setText("By HSCODE");

        report_hs_code_s.setText("HSCODE");
        report_hs_code_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_hs_code_sActionPerformed(evt);
            }
        });
        report_hscode.add(report_hs_code_s);

        jMenu2.add(report_hscode);
        jMenu2.add(jSeparator4);

        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu9);

        menu_tools.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_tools.setText("Tools    ");

        jMenuItem3.setText("Backup");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu_tools.add(jMenuItem3);

        tools_restore.setText("Restore");
        menu_tools.add(tools_restore);

        jMenuBar1.add(menu_tools);

        jMenu4.setText("Help");

        help_help.setText("Help");
        help_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_helpActionPerformed(evt);
            }
        });
        jMenu4.add(help_help);

        help_about.setText("About......");
        help_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_aboutActionPerformed(evt);
            }
        });
        jMenu4.add(help_about);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(jLabel1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_add_userActionPerformed
        // TODO add your handling code here:
        Newuser adduser;
        try {
            adduser = new Newuser(eUser);
            desktop.add(adduser);
            centerDesktop centerDesktop = new centerDesktop(desktop, adduser);        
            adduser.show();
        } catch (ParserConfigurationException | IOException | SAXException | XPathExpressionException | URISyntaxException ex) {
            JOptionPane.showMessageDialog(menu_company, ex);
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_menu_add_userActionPerformed

    private void menu_edit_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_edit_userActionPerformed
        // TODO add your handling code here:
//        edituser edit = new edituser();
//        desktop.add(edit);
//        edit.show();
        
        
        userEdit jt = new userEdit(eUser);
        desktop.add(jt);
        centerDesktop centerDesktop = new centerDesktop(desktop, jt);
        jt.show();
        
        
        
    }//GEN-LAST:event_menu_edit_userActionPerformed

    private void help_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_helpActionPerformed
        // TODO add your handling code here:
        Help edit_help = new Help();
        desktop.add(edit_help);
        centerDesktop centerDesktop = new centerDesktop(desktop, edit_help);
        edit_help.show();
    }//GEN-LAST:event_help_helpActionPerformed

    private void help_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_aboutActionPerformed
        // TODO add your handling code here:
        About edit_about = new About();
        desktop.add(edit_about);
        centerDesktop centerDesktop = new centerDesktop(desktop, edit_about);
        edit_about.show();
    }//GEN-LAST:event_help_aboutActionPerformed

    private void data_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_inputActionPerformed
        // TODO add your handling code here:
        Import edit_import = new Import();
        desktop.add(edit_import);
        centerDesktop centerDesktop = new centerDesktop(desktop, edit_import);
        edit_import.show();
        
    }//GEN-LAST:event_data_inputActionPerformed

    private void edit_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_dataActionPerformed
        // TODO add your handling code here:
        editimport e_port = new editimport();
        desktop.add(e_port);
        centerDesktop centerDesktop = new centerDesktop(desktop, e_port);
        e_port.show();
    }//GEN-LAST:event_edit_dataActionPerformed

    private void menu_companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_companyActionPerformed
        // TODO add your handling code here:
        Editcompany company = new Editcompany();
        desktop.add(company);
        centerDesktop centerDesktop = new centerDesktop(desktop, company);
        company.show();
    }//GEN-LAST:event_menu_companyActionPerformed

    private void menu_officeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_officeActionPerformed
        // TODO add your handling code here:
        editoffice off = new editoffice();
        desktop.add(off);
        centerDesktop centerDesktop = new centerDesktop(desktop, off);
        off.show();
    }//GEN-LAST:event_menu_officeActionPerformed

    private void menu_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_countryActionPerformed
        // TODO add your handling code here:
         editcountry off = new editcountry();
        desktop.add(off);
        centerDesktop centerDesktop = new centerDesktop(desktop, off);
        off.show();
    }//GEN-LAST:event_menu_countryActionPerformed

    private void menu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_exitActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_menu_exitActionPerformed

    private void menu_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_logoutActionPerformed
        try {
            this.setVisible(false);
            Login ll = new Login();
            ll.setVisible(true);
        } catch (ParserConfigurationException | SAXException | IOException | XPathExpressionException | URISyntaxException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }//GEN-LAST:event_menu_logoutActionPerformed

    private void report_date_wiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_date_wiseActionPerformed
        // TODO add your handling code here:
        Report_date rep = new Report_date();
        desktop.add(rep);
        centerDesktop centerDesktop = new centerDesktop(desktop, rep);
        rep.show();
    }//GEN-LAST:event_report_date_wiseActionPerformed

    private void report_date_date_hscodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_date_date_hscodeActionPerformed
        Report_date_hscode rep = new Report_date_hscode ();
        desktop.add(rep);
        centerDesktop centerDesktop = new centerDesktop(desktop, rep);
        rep.show();
    }//GEN-LAST:event_report_date_date_hscodeActionPerformed

    private void report_hs_code_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_hs_code_sActionPerformed
           Report_hscode rep = new Report_hscode();
           desktop.add(rep);
           centerDesktop centerDesktop = new centerDesktop(desktop, rep);
           rep.show();
    }//GEN-LAST:event_report_hs_code_sActionPerformed

    private void release_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release_importActionPerformed
        // TODO add your handling code here:
        importRelease release = new importRelease(eUser);
        desktop.add(release);
        centerDesktop centerDesktop = new centerDesktop(desktop, release);
        release.show();
    }//GEN-LAST:event_release_importActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        export exp = new export();
        desktop.add(exp);
        centerDesktop centerDesktop = new centerDesktop(desktop, exp);
        exp.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        editexport exp = new editexport();
        desktop.add(exp);
        centerDesktop centerDesktop = new centerDesktop(desktop, exp);
        exp.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        exportRelease exp = new exportRelease(eUser);
        desktop.add(exp);
        centerDesktop centerDesktop = new centerDesktop(desktop, exp);
        exp.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        
        // TODO add your handling code here:
        String dbUserName = "root";
        String dbPassword = "kishor";
        String dbName = "test";
        String path = "sqldabase.sql";
        
        String executeCmd = "mysqldump -u " + dbUserName + " -p" + dbPassword + " --add-drop-database -B " + dbName + " -r " + path;
        Process runtimeProcess;
        try {
 
            runtimeProcess = Runtime.getRuntime().exec(executeCmd);
            int processComplete = runtimeProcess.waitFor();
 
            if (processComplete == 0) {
                JOptionPane.showMessageDialog(menu_company,"Backup created successfully");
                System.out.println("Backup created successfully");
//                return true;
            } else {
                System.out.println("Could not create the backup");
            }
        } catch (IOException | InterruptedException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu custom_export;
    private javax.swing.JMenu customs_import;
    private javax.swing.JMenuItem data_input;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem edit_data;
    private javax.swing.JMenuItem help_about;
    private javax.swing.JMenuItem help_help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenu main_menu;
    private javax.swing.JMenuItem menu_add_user;
    private javax.swing.JMenuItem menu_company;
    private javax.swing.JMenuItem menu_country;
    private javax.swing.JMenuItem menu_edit_user;
    private javax.swing.JMenuItem menu_exit;
    private javax.swing.JMenuItem menu_logout;
    private javax.swing.JMenuItem menu_office;
    private javax.swing.JMenu menu_tools;
    private javax.swing.JMenuItem release_import;
    private javax.swing.JMenu report_by_date;
    private javax.swing.JMenuItem report_date_date_hscode;
    private javax.swing.JMenuItem report_date_wise;
    private javax.swing.JMenuItem report_hs_code_s;
    private javax.swing.JMenu report_hscode;
    private javax.swing.JMenuItem tools_restore;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
